version: "3"

services:
    influxdb:
        build: ./influxdb
        container_name: influxdb
        ports:
            - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
        volumes:
            - /var/lib/influxdb:/var/lib/influxdb
        restart: always
        env_file:
            - .env
        networks:
            - backend
            - frontend

    telegraf:
        build: ./telegraf
        container_name: telegraf
        links:
            - influxdb
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/hostfs/proc
        privileged: true
        restart: always
        env_file:
            - .env
        networks: 
            - backend
            
    grafana:
        build: ./grafana
        container_name: grafana
        ports: 
            - ${GRAFANA_PORT}:${GRAFANA_PORT}
        links:
            - influxdb
        volumes:
            - /var/lib/grafana
            - /var/log/grafana
            - /var/lib/grafana/plugins
        restart: always
        env_file:
            - .env
        networks:
            - frontend

    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
        - "80:80"
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
        - grafana
        networks:
        - backend
        - frontend

    webapp:
        build: ./webapp
        container_name: webapp
        ports:
        - "8080:8080"
        networks:
        - backend
networks:
    backend:
    frontend:
